server:
  port: 8082

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/logistic"
    username: "postgres"
    password: "nguyenhungvy09"

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always
      schema-locations: classpath:oct_l2_logistic.sql
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: "logs/info.log"
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%"
  logback:
    rollingpolicy:
      max-file-size: 2MB
      total-size-cap: 10MB
      max-history: 30
      clean-history-on-start: false
